services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - ./backend/.env.development
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20

  api:
    image: node:20-alpine
    working_dir: /app
    command: >
      sh -c "npm install &&
      npx prisma generate --schema=./src/infra/database/prisma/schema.prisma &&
      npm run dev"
    env_file:
      - ./backend/.env.development
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3333:3333"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: node:20-alpine
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=/api
      - VITE_API_TARGET=http://api:3333
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5180:5180"
    depends_on:
      api:
        condition: service_started

volumes:
  mysql_data:
